#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 190

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rdXPn/gaqlzN"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

