#define FLOW_TAP_TERM 20
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rdXPn/AzwJ4R"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

// Custom configuration
#define VOYAGER_USER_LEDS
#define CAPS_WORD_IDLE_TIMEOUT 0
